// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AjaxBar: typeof import('./components/AjaxBar.vue')['default']
    BannerCover: typeof import('./components/BannerCover.vue')['default']
    BannerSkeletion: typeof import('./components/skeleton/BannerSkeletion.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    CardSkeletion: typeof import('./components/skeleton/CardSkeletion.vue')['default']
    DesImg: typeof import('./components/DesImg.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElKeleton: typeof import('element-plus/es')['ElKeleton']
    ElKeletonIten: typeof import('element-plus/es')['ElKeletonIten']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMemuItem: typeof import('element-plus/es')['ElMemuItem']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSkeletonIten: typeof import('element-plus/es')['ElSkeletonIten']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabel: typeof import('element-plus/es')['ElTabel']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    GameBox: typeof import('./components/GameEmulator.vue')['default']
    GameCard: typeof import('./components/GameCard.vue')['default']
    GameCover: typeof import('./components/GameCover.vue')['default']
    GameEmulator: typeof import('./components/GameEmulator.vue')['default']
    IconControl: typeof import('./components/IconControl.vue')['default']
    IconInner: typeof import('./components/IconInner.vue')['default']
    IconOutside: typeof import('./components/IconOutside.vue')['default']
    InnerLoading: typeof import('./components/InnerLoading.vue')['default']
    KeyboardOption: typeof import('./components/KeyboardOption.vue')['default']
    KeySquare: typeof import('./components/KeySquare.vue')['default']
    MainFooter: typeof import('./components/MainFooter.vue')['default']
    MainHeader: typeof import('./components/MainHeader.vue')['default']
    RecomBox: typeof import('./components/RecomBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    TBanner: typeof import('./components/TBanner.vue')['default']
    TestVue: typeof import('./components/TestVue.vue')['default']
    VolumeKnob: typeof import('./components/VolumeKnob.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
